### PR TITLE
Command additions

### PR DESCRIPTION
**Pull request by memequester**
Added the `betterjoy` and `ds4` commands to display github links and info for BetterJoy and DS4windows.
Also updated the piracy text to better reflect the anti-piracy stance of the server.

### CODE REVIEW

**Comment by memequester** [comment]
just occurred to me that we use Dyno for piracy messages... might leave that text as-is so it matches Dyno's message.

**Comment by memequester** [comment]
@AlexApps99 sorry for the ping, can I get a review of this?

**Comment by AlexApps99** [comment]
I can't test it, but I don't see any problems with it.
I'm not on the server anymore, so if you can just verify that you are staff (or that a staff member has approved of the contents of the PR) I'd be happy to merge

**Comment by memequester** [comment]
Screenshot_20220423-111919 I'm support staff on the server, but Cobalt or Mangler could maybe take a look if you'd prefer

**Comment by SirMangler** [comment]
I can confirm Meme is a support staff, I'd like the actual messages to be ran by the other support staff/mods for sanity. But I don't feel confident about reviewing this, mainly because I can't test it to ensure it doesn't break anything.

**Comment by AlexApps99** [comment]
@memequester cool, I'll merge it.
If the bot breaks/doesn't update, let me know quick so I can revert/fix the changes.

**Comment by AlexApps99** [comment]
> I can confirm Meme is a support staff, I'd like the actual messages to be ran by the other support staff/mods for sanity. But I don't feel confident about reviewing this, mainly because I can't test it to ensure it doesn't break anything.

Never mind, I'll wait for another staff member. :+1:

**Comment by Neelgodly** [comment]
The piracy command says 'previously owning the game does not make downloading it legal' which gives the impression that downloading is legal if you still own the game. I feel the word 'previously' should be removed.

I'm ZeVillain btw, pretty new support staff but the rest of it looks fine to me :)

**Comment by memequester** [comment]
> The piracy command says 'previously owning the game does not make downloading it legal' which gives the impression that downloading is legal if you still own the game. 
imo "Piracy is illegal, and is not tolerated in this server. Previously owning a game does not make downloading the game legal" is already clear (it states that piracy is illegal, and the most common excuse people provide is not valid) but I suppose "Owning or previously owning" might be clearer. I'll see what Cobalt or another higherup thinks

**Comment by memequester** [comment]
Clarified and also updated the automessage embed to match the piracy command's embed

I'll also look into making the bot work with both / and d! as prefixes, that'll be in a different PR though

**Comment by cobalt2727** [comment]
I take full responsibility for any bugs, crashes, or nuclear apocalypses that may result from this merge.

**Comment by cobalt2727** [comment]
@AlexApps99 do we have to restart the bot for these changes to take effect?

**Comment by AlexApps99** [comment]
It should do it automatically.
Did it work?

**Comment by AlexApps99** [comment]
https://status.heroku.com/incidents/2413
Perhaps this is causing the issue - I got an email some hours ago:

> An automatic deployment for dolphindiscord failed. The build failed with the message
> `Unauthorized`.
>
> Token from user [email] was used to interact with GitHub. This account was matched as the GitHub committer.
>
> You can also check that the user who connected the app or pipeline to GitHub still has access to the app and to the Github repository.
>
> In this case, reconnecting to GitHub will often fix the issue.

When I tried to reconnect, Heroku would spit out errors.
So we'll probably need to wait out this security issue, or upload manually.

**Comment by cobalt2727** [comment]
I think you'll need to regenerate a token yourself, judging by the error

**Comment by AlexApps99** [comment]
That won't work (see the link)

**Comment by memequester** [comment]
it's only Heroku's Github integration which is down, so manually pushing the changes from github still works (and is what they advise doing in the meantime). should just be `git push heroku main`

**Comment by AlexApps99** [comment]
It's not so simple, I'd need to install and setup `heroku-cli` on my machine beforehand.

Waiting out the fix and getting automatic deployment working again would be easier, but if you insist on deploying now, I could always try set it up later when I have access.

**Comment by cobalt2727** [comment]
Up to you - it's not a pressing issue.

**Comment by AlexApps99** [comment]
I ended up deploying it.
Let me know if there are any issues, I will uninstall the CLI tool if I don't hear anything by tomorrow.

**Comment by cobalt2727** [comment]
Everything looks good!
@memequester - nice work.

**Pull request merged**
