### PR TITLE
Redirect all help queries to Laz DMs

### PR DESCRIPTION
**Pull request by jkcoxson**
Check https://discord.com/channels/521709831132807179/549875374327332884/830665542904971304 for context.

### CODE REVIEW

**Review by CrusadingNinja — APPROVED** [review]
good stuff

**Comment by cobalt2727** [comment]
I completely support this.

**Comment by jkcoxson** [comment]
Laz isn't even on the Discord team anymore, so....

**Comment by AlexApps99** [comment]
Regrettably, this can't be merged anymore. Feel free to open another PR sometime before April of next year, though

**Pull request closed without merging**
